---
- name: Install Docker and add jenkins user to docker group
  hosts: localhost
  become: true

  tasks:
    - name: Update server OS packages
      ansible.builtin.command: dnf update -y

    - name: Add Docker CE repository
      ansible.builtin.command: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo

    - name: Remove old Docker packages
      ansible.builtin.command: dnf remove -y docker docker-common docker-selinux docker-engine

    - name: Install Docker CE, Docker CLI, Containerd, and Docker Compose
      ansible.builtin.command: dnf install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin --best --allowerasing
