---
- hosts: localhost
  become: yes
  become_user: root
  tasks:
  - name: yum update
    yum:
      name: '*'
      state: latest

  - name: Install java
    yum:
      name: java-11-openjdk-devel
      state: present

  - name: Install Maven
    yum:
      name: maven
      state: present
